# Generated by Django 3.0.4 on 2020-05-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThrasherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_author',
            field=models.CharField(default='', max_length=200),
        ),
    ]
