# Generated by Django 3.0.4 on 2020-05-14 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThrasherApp', '0002_review_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_grade',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
